name: CI/CD
on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  packages: write   # allow pushing to GHCR

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (sanity check)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m py_compile invoice_app.py etl.py

      - name: Set image meta
        id: meta
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${REPO_LC}/elevators-app" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "TAG_LATEST=latest" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build prod image (no ETL baked in)
      - name: Build (prod)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.TAG_SHA }}
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.TAG_LATEST }}
          build-args: |
            APP_ENV=prod

      # Optional: ping Render Deploy Hook to redeploy with the new image
      # Create a "Deploy Hook" in Render and save the URL as a secret: RENDER_DEPLOY_HOOK
      - name: Trigger Render deploy
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
