name: CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write   # needed to push to GHCR

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (optional) quick sanity check — keep if you like
      - name: Sanity check
        run: |
          test -f Dockerfile || { echo "Dockerfile missing"; exit 1; }
          python -m py_compile invoice_app.py etl.py

      - name: Set image meta
        id: meta
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${REPO_LC}/elevators-app" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "TAG_LATEST=latest" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.TAG_SHA }}
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.TAG_LATEST }}

      # 🔔 Auto-redeploy Render (service-specific Deploy Hook URL stored as a secret)
      - name: Trigger Render deploy (if configured)
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK" ]; then
            echo "Triggering Render deploy..."
            curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
          else
            echo "No RENDER_DEPLOY_HOOK set; skipping."
          fi
